### ISSUE TITLE
Additional Requirement

### ISSUE THREAD

**Issue by balajpri2021** [balajpri2021/Group-6#1]
Dear Developers,
Regarding the website design, I kindly ask that you include a breadcrumb navigation similar to the one below, using our website's color scheme.
![image](https://user-images.githubusercontent.com/93986263/148302304-3f42105d-adff-4175-8e73-1dec83945fb0.png)

Thanks in advance

**Comment by jessicabrummack** [comment]
Alright, we can do that :)

**Comment by jessicabrummack** [comment]
Should this replace the navigation bar at the top of your pages?

**Comment by balajpri2021** [comment]
### No 
It should not replace the global navigation bar it should be below the navigation bar, The navigation bar is pinned to all the webpages. but the breadcrumb navigation will differ for each webpage clicked. 
Please refer [https://www.nngroup.com/articles/breadcrumbs/](url) for clear clarification on how navigation bar and breadcrumbs navigation are used.

Also you can modify the breadcrumbs navigation styles as you wish which you feel looks good on the website. 
 
Hope this clarifies your doubt.

**Comment by jessicabrummack** [comment]
Okay, thank you for the clarification!
