### ISSUE TITLE
Can't access branch "gh-pages"

### ISSUE THREAD

**Issue by rbakosBTU** [balajpri2021/Group-6#2]
Hello,

could you please check my access to the repository? Unfortunately, I can't push into the repository.

Thanks in advance.

**Comment by balajpri2021** [comment]
Hi,
It's probably because you **haven't accepted** the invitation to collaborate. I've sent you **another invitation**; please accept it and let me know whether you're able to complete the "push" action.

Thanks.

**Comment by rbakosBTU** [comment]
Hello,

thank you for your quick response! I just accepted the invitation.
