### ISSUE TITLE
gh-pages setup

### ISSUE THREAD

**Issue by jessicabrummack** [balajpri2021/Group-6#4]
Hello,

our Git Hub Pages doesn't work from the gh-pages branch. Could you please set this up?
You need to go to 

- **Settings** -> **Pages**
- change the source branch from **main** to **gh-pages**
- and also from **/(root)** to **assignment 2b/docs**

Thanks in advance

**Comment by balajpri2021** [comment]
Hi,
The Git Hub Page works fine  [index.html](https://balajpri2021.github.io/Group-6/assignment%202b/docs/index.html). Please use the proper path to deploy and view the page

Thanks.

**Comment by jessicabrummack** [comment]
Thank you, we just didn't had the right link.
