### ISSUE TITLE
Missing credit information

### ISSUE THREAD

**Issue by jessicabrummack** [balajpri2021/Group-6#6]
Hello,

in your credits.html file, the "Women 4" image is marked with a CC BY 2.0 license. According to this license you have to name the creator and provide a link, but i couldn't find any name or source. Do you have something like that for this image?

**Comment by balajpri2021** [comment]
Hi,
Please use the following
"Jimm Choo Women Shoes Collection" by foeock is licensed under CC BY 2.0

**Comment by jessicabrummack** [comment]
Okay, thank you!
